In [1]:
import tensorflow as tf
print(tf.__version__)

1.11.0


In [3]:
hello = tf.constant("Hello ")

In [10]:
world = tf.constant("World")

In [11]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [12]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [13]:
print(result)

b'Hello World'


In [14]:
a = tf.constant(10)
b = tf.constant(20)
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [17]:
type(result)

numpy.int32

In [30]:
const = tf.constant(10)

In [31]:
fill_mat = tf.fill((4,4),10)

In [32]:
myzeros = tf.zeros((4,4))

In [33]:
myones = tf.ones((4,4))

In [34]:
myrand = tf.random_normal((4,4),mean = 0,stddev=1.0)

In [35]:
myuniform = tf.random_uniform((4,4),minval=0, maxval=1)

In [36]:
myzeros

<tf.Tensor 'zeros_2:0' shape=(4, 4) dtype=float32>

In [37]:
my_ops = [const,fill_mat,myzeros,myones,myrand,myuniform]

In [38]:
sess = tf.InteractiveSession()

c:\miniconda3\envs\tensorflow-env\lib\site-packages\tensorflow\python\client\session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [40]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.3584559  -0.60893375 -0.03997822 -0.6911184 ]
 [ 0.45130157  0.3689362   0.8491259   0.8664326 ]
 [-1.6274632  -0.5528055   0.41702458  1.5940037 ]
 [-1.0242406   0.9472238   1.4734707  -0.6455885 ]]


[[0.0549432  0.44441473 0.47985065 0.0354532 ]
 [0.89669454 0.26766455 0.17205942 0.7982998 ]
 [0.8888413  0.8224143  0.2086879  0.36598504]
 [0.35158396 0.7102237  0.6750046  0.9060433 ]]




In [41]:
a = tf.constant([[1,2],
                 [3,4]])

In [42]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [43]:
b = tf.constant([[10],[100]])

In [44]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [45]:
result = tf.matmul(a,b)

In [46]:
sess.run(result)

array([[210],
       [430]])